text(1,"I").
lemma(1,"I").
upos(1,"PRON").
xpos(1,"PRP").
feats(1,"Case=Nom|Number=Sing|Person=1|PronType=Prs").
head(1,3).
deprel(1,"nsubj").
text(2,"actually").
lemma(2,"actually").
upos(2,"ADV").
xpos(2,"RB").
head(2,3).
deprel(2,"advmod").
text(3,"like").
lemma(3,"like").
upos(3,"VERB").
xpos(3,"VBP").
feats(3,"Mood=Ind|Tense=Pres|VerbForm=Fin").
head(3,0).
deprel(3,"root").
text(4,"him").
lemma(4,"he").
upos(4,"PRON").
xpos(4,"PRP").
feats(4,"Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs").
head(4,3).
deprel(4,"obj").
text(5,".").
lemma(5,".").
upos(5,"PUNCT").
xpos(5,".").
head(5,3).
deprel(5,"punct").
is_subj_of_pred(SUBJ,PRED):-head(SUBJ_NUM,PRED_NUM),deprel(SUBJ_NUM,"nsubj"),upos(PRED_NUM,"VERB"),text(SUBJ_NUM,SUBJ),text(PRED_NUM,PRED).