text(1,"I").
lemma(1,"I").
upos(1,"PRON").
xpos(1,"PRP").
feats(1,"Case=Nom|Number=Sing|Person=1|PronType=Prs").
head(1,2).
deprel(1,"nsubj").
text(2,"like").
lemma(2,"like").
upos(2,"VERB").
xpos(2,"VBP").
feats(2,"Mood=Ind|Tense=Pres|VerbForm=Fin").
head(2,0).
deprel(2,"root").
text(3,"him").
lemma(3,"he").
upos(3,"PRON").
xpos(3,"PRP").
feats(3,"Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs").
head(3,2).
deprel(3,"obj").
text(4,".").
lemma(4,".").
upos(4,"PUNCT").
xpos(4,".").
head(4,2).
deprel(4,"punct").
author(_author,_work):-  semantic(生成),type(X0,verb),(  main(X0,書く);  main(X0,描く)),role(X1,動作主),main(X1,_author),role(X2,対象),main(X2,_work)